# Use the official Rust image as the base image
FROM rust:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the necessary files into the container
COPY . /app

# # Set the environment variable for Rust logging
# ENV RUST_LOG="info"

# RUN apt-get update && apt-get -y upgrade && apt-get install -y libclang-dev pkg-config

# # Build the application
# RUN cargo build --release

# # Define the entrypoint to run the shell script
# ENTRYPOINT ["/bin/bash", "app/scripts/run_node.sh"]

